all:
  children:
    pilot_gmc:
      hosts:
        agcmr1:
        agcmr2:
        agcmr3:
    pis:
      hosts:
        agcmr1:
          ansible_host: 100.110.245.105
          ansible_user: agcmr1
          ansible_ssh_private_key_file: /home/mlweb/.ssh/mri_pi_fleet_ed25519
          ansible_python_interpreter: /usr/bin/python3
        agcmr2:
          ansible_host: 100.94.132.85
          ansible_user: mrcu
          ansible_ssh_private_key_file: /home/mlweb/.ssh/mri_pi_fleet_ed25519
          ansible_python_interpreter: /usr/bin/python3
        agcmr3:
          ansible_host: 100.103.6.98
          ansible_port: 2222
          ansible_user: agcmr3
          ansible_ssh_private_key_file: /home/mlweb/.ssh/mri_pi_fleet_ed25519
          ansible_python_interpreter: /usr/bin/python3
        svimr2:
          ansible_host: 100.117.38.77
          ansible_user: svimr2
          ansible_ssh_private_key_file: /home/mlweb/.ssh/mri_pi_fleet_ed25519
          ansible_python_interpreter: /usr/bin/python3
        pittstonsola:
          ansible_host: 100.86.162.63
          ansible_user: pts
          ansible_ssh_private_key_file: /home/mlweb/.ssh/mri_pi_fleet_ed25519
          ansible_python_interpreter: /usr/bin/python3
        pittstonvida:
          ansible_host: 100.75.151.96
          ansible_user: ptv
          ansible_ssh_private_key_file: /home/mlweb/.ssh/mri_pi_fleet_ed25519
          ansible_python_interpreter: /usr/bin/python3
        gcmcsola:
          ansible_host: 100.106.107.124
          ansible_user: gcmc
          ansible_ssh_private_key_file: /home/mlweb/.ssh/mri_pi_fleet_ed25519
          ansible_python_interpreter: /usr/bin/python3
        gcmcmr2:
          ansible_host: 100.67.249.11
          ansible_user: gcmc2
          ansible_ssh_private_key_file: /home/mlweb/.ssh/mri_pi_fleet_ed25519
          ansible_python_interpreter: /usr/bin/python3
        gswbsola:
          ansible_host: 100.99.117.107
          ansible_user: gswb
          ansible_ssh_private_key_file: /home/mlweb/.ssh/mri_pi_fleet_ed25519
          ansible_python_interpreter: /usr/bin/python3
        gwvs:
          ansible_host: 100.82.46.17
          ansible_user: gwvs
          ansible_ssh_private_key_file: /home/mlweb/.ssh/mri_pi_fleet_ed25519
          ansible_python_interpreter: /usr/bin/python3
        gwvskyra:
          ansible_host: 100.113.100.18
          ansible_user: gwv
          ansible_ssh_private_key_file: /home/mlweb/.ssh/mri_pi_fleet_ed25519
          ansible_python_interpreter: /usr/bin/python3
        vwm1:
          ansible_host: 100.93.88.121
          ansible_user: vwm1
          ansible_ssh_private_key_file: /home/mlweb/.ssh/mri_pi_fleet_ed25519
          ansible_python_interpreter: /usr/bin/python3
        vwm2:
          ansible_host: 100.126.97.119
          ansible_user: vwm2
          ansible_ssh_private_key_file: /home/mlweb/.ssh/mri_pi_fleet_ed25519
          ansible_python_interpreter: /usr/bin/python3
        vwm3:
          ansible_host: 100.88.55.37
          ansible_user: vwm3
          ansible_ssh_private_key_file: /home/mlweb/.ssh/mri_pi_fleet_ed25519
          ansible_ssh_common_args: -o IdentitiesOnly=yes
          ansible_python_interpreter: /usr/bin/python3
